Route102_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route103_EventScript_ItemGuardSpec::
	finditem ITEM_GUARD_SPEC
	end

Route103_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route104_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

Route104_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route105_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route106_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route108_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route109_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route109_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route110_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route110_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

Route110_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route111_EventScript_ItemTM37::
	finditem ITEM_TM37
	end

Route111_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route111_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route112_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route113_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Route113_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route113_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route114_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route114_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route114_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route115_EventScript_ItemTM01::
	finditem ITEM_TM01
	end

Route115_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route115_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route116_EventScript_ItemXSpecial::
	finditem ITEM_X_SP_ATK
	end

Route116_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route116_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route116_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route116_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route117_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route117_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route118_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route119_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route119_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route119_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

Route119_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route119_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemHyperPotion2::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemElixir2::
	finditem ITEM_ELIXIR
	end

Route120_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route120_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route120_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route121_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route123_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

Route123_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route123_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route123_EventScript_ItemRevivalHerb::
	finditem ITEM_REVIVAL_HERB
	end

Route124_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route127_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route127_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Route134_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

PetalburgCity_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

PetalburgCity_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

MauvilleCity_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

RustboroCity_EventScript_ItemXDefend::
	finditem ITEM_X_DEFENSE
	end

LilycoveCity_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

PetalburgWoods_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

PetalburgWoods_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

PetalburgWoods_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

RusturfTunnel_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

RusturfTunnel_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

GraniteCave_1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

GraniteCave_B1F_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

GraniteCave_B2F_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

GraniteCave_B2F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

JaggedPass_EventScript_ItemBurnHeal::
	finditem ITEM_BURN_HEAL
	end

FieryPath_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemTM06::
	finditem ITEM_TM06
	end

MeteorFalls_1F_1R_EventScript_ItemTM23::
	finditem ITEM_TM23
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP::
	finditem ITEM_PP_UP
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02::
	finditem ITEM_TM02
	end

NewMauville_Inside_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

NewMauville_Inside_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

NewMauville_Inside_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
	finditem ITEM_DIVE_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13::
	finditem ITEM_TM13
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
	finditem ITEM_TM18
	end

ScorchedSlab_EventScript_ItemTM11::
	finditem ITEM_TM11
	end

SafariZone_Northwest_EventScript_ItemTM22::
	finditem ITEM_TM22
	end

SafariZone_North_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

MtPyre_3F_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemLaxIncense::
	finditem ITEM_LAX_INCENSE
	end

MtPyre_6F_EventScript_ItemTM30::
	finditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemTM48::
	finditem ITEM_TM48
	end

AquaHideout_B1F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

SeafloorCavern_Room9_EventScript_ItemTM26::
	finditem ITEM_TM26
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

VictoryRoad_B1F_EventScript_ItemTM29::
	finditem ITEM_TM29
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

ArtisanCave_B1F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

MagmaHideout_3F_1R_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

Route103_EventScript_ItemOranBerry::
	finditem ITEM_ORAN_BERRY
	end

Route103_EventScript_ItemQuickClaw::
	finditem ITEM_QUICK_CLAW
	end

Route103_EventScript_ItemSilkScarf::
	finditem ITEM_SILK_SCARF
	end

Route104_EventScript_ItemAmuletCoin::
	finditem ITEM_AMULET_COIN
	end

Route104_EventScript_ItemCheriBerry::
	finditem ITEM_CHERI_BERRY
	end

Route104_EventScript_ItemChestoBerry::
	finditem ITEM_CHESTO_BERRY
	end

Route105_EventScript_ItemCellBattery::
	finditem ITEM_CELL_BATTERY
	end

Route105_EventScript_ItemEviolite::
	finditem ITEM_EVIOLITE
	end

Route105_EventScript_ItemLaggingTail::
	finditem ITEM_LAGGING_TAIL
	end

Route105_EventScript_ItemMentalHerb::
	finditem ITEM_WAILMER_PAIL
	setflag FLAG_RECEIVED_WAILMER_PAIL
	end

Route105_EventScript_ItemDampMulch::
	finditem ITEM_DAMP_MULCH
	end

Route105_EventScript_ItemGrowthMulch::
	finditem ITEM_GROWTH_MULCH
	end

Route105_EventScript_ItemRichMulch::
	finditem ITEM_RICH_MULCH
	end


Route106_EventScript_ItemMuscleBand::
	finditem ITEM_MUSCLE_BAND
	end

Route106_EventScript_ItemZoomLens::
	finditem ITEM_ZOOM_LENS
	end

Route106_EventScript_ItemPowerBelt::
	finditem ITEM_POWER_BELT
	end

Route106_EventScript_ItemPowerLens::
	finditem ITEM_POWER_LENS
	end

Route106_EventScript_ItemPowerBand::
	finditem ITEM_POWER_BAND
	end

Route106_EventScript_ItemPechaBerry::
	finditem ITEM_PECHA_BERRY
	end

Route106_EventScript_ItemPersimBerry::
	finditem ITEM_PERSIM_BERRY
	end

Route108_EventScript_ItemCharcoal::
	finditem ITEM_CHARCOAL
	end

Route108_EventScript_ItemMagnet::
	finditem ITEM_MAGNET
	end

Route108_EventScript_ItemSharpBeak::
	finditem ITEM_SHARP_BEAK
	end

Route108_EventScript_ItemDestinyKnot::
	finditem ITEM_DESTINY_KNOT
	end

Route108_EventScript_ItemBindingBand::
	finditem ITEM_BINDING_BAND
	end

Route108_EventScript_ItemShedShell::
	finditem ITEM_SHED_SHELL
	end
	
Chapter4_EventScript_MysticWater::
    finditem ITEM_MYSTIC_WATER
    end

Chapter4_EventScript_WhiteHerb::
    finditem ITEM_WHITE_HERB
    end

Chapter4_EventScript_WiseGlasses::
    finditem ITEM_WISE_GLASSES
    end

Chapter4_EventScript_MiracleSeed::
    finditem ITEM_MIRACLE_SEED
    end

Chapter5_EventScript_Nevermeltice::
    finditem ITEM_NEVER_MELT_ICE
    end

Chapter5_EventScript_FloatStone::
    finditem ITEM_FLOAT_STONE
    end

Chapter5_EventScript_AmuletCoin::
    finditem ITEM_AMULET_COIN
    end

Chapter5_EventScript_MetalCoat::
    finditem ITEM_METAL_COAT
    end

Chapter5_EventScript_PoisonBarb::
    finditem ITEM_POISON_BARB
    end

Chapter5_EventScript_GripClaw::
    finditem ITEM_GRIP_CLAW
    end

Chapter6_EventScript_BlackBelt::
    finditem ITEM_BLACK_BELT
    end

Chapter6_EventScript_SoftSand::
    finditem ITEM_SOFT_SAND
    end

Chapter6_EventScript_TwistedSpoon::
    finditem ITEM_TWISTED_SPOON
    end

Chapter6_EventScript_EjectPack::
    finditem ITEM_EJECT_PACK
    end

Chapter6_EventScript_BrightPowder::
    finditem ITEM_BRIGHT_POWDER
    end

Chapter6_EventScript_IronBall::
    finditem ITEM_IRON_BALL
    end

Chapter6_EventScript_BigRoot::
    finditem ITEM_BIG_ROOT
    end

Chapter6_EventScript_LumBerry::
    finditem ITEM_LUM_BERRY
    end

Chapter6_EventScript_SitrusBerry::
    finditem ITEM_SITRUS_BERRY
    end

Chapter6_EventScript_KebiaBerry::
    finditem ITEM_KEBIA_BERRY
    end

Chapter7_EventScript_SpellTag::
    finditem ITEM_SPELL_TAG
    end

Chapter7_EventScript_DragonFang::
    finditem ITEM_DRAGON_FANG
    end

Chapter7_EventScript_HardStone::
    finditem ITEM_HARD_STONE
    end

Chapter7_EventScript_RedCard::
    finditem ITEM_RED_CARD
    end

Chapter7_EventScript_RazorFang::
    finditem ITEM_RAZOR_FANG
    end

Chapter7_EventScript_ScopeLens::
    finditem ITEM_SCOPE_LENS
    end

Chapter7_EventScript_Metronome::
    finditem ITEM_METRONOME
    end

Chapter7_EventScript_AdrenalineOrb::
    finditem ITEM_ADRENALINE_ORB
    end

Chapter7_EventScript_PasshoBerry::
    finditem ITEM_PASSHO_BERRY
    end

Chapter7_EventScript_KeeBerry::
    finditem ITEM_KEE_BERRY
    end

Chapter7_EventScript_MarangaBerry::
    finditem ITEM_MARANGA_BERRY
    end

Chapter8_EventScript_RockyHelmet::
    finditem ITEM_ROCKY_HELMET
    end

Chapter8_EventScript_FocusBand::
    finditem ITEM_FOCUS_BAND
    end

Chapter8_EventScript_Leftovers::
    finditem ITEM_LEFTOVERS
    end

Chapter8_EventScript_FigyBerry::
    finditem ITEM_FIGY_BERRY
    end

Chapter8_EventScript_MagoBerry::
    finditem ITEM_MAGO_BERRY
    end

Chapter8_EventScript_KasibBerry::
    finditem ITEM_KASIB_BERRY
    end

Chapter8_EventScript_ChilanBerry::
    finditem ITEM_CHILAN_BERRY
    end

Chapter8_EventScript_OccaBerry::
    finditem ITEM_OCCA_BERRY
    end

Chapter8_EventScript_ChopleBerry::
    finditem ITEM_CHOPLE_BERRY
    end

Chapter8_EventScript_ShucaBerry::
    finditem ITEM_SHUCA_BERRY
    end

Chapter9_EventScript_AbsorbBulb::
    finditem ITEM_ABSORB_BULB
    end

Chapter9_EventScript_StickyBarb::
    finditem ITEM_STICKY_BARB
    end

Chapter9_EventScript_KingsRock::
    finditem ITEM_KINGS_ROCK
    end

Chapter9_EventScript_WideLens::
    finditem ITEM_WIDE_LENS
    end

Chapter9_EventScript_WikiBerry::
    finditem ITEM_WIKI_BERRY
    end

Chapter9_EventScript_AguavBerry::
    finditem ITEM_AGUAV_BERRY
    end

Chapter9_EventScript_IapapaBerry::
    finditem ITEM_IAPAPA_BERRY
    end

Chapter9_EventScript_WacanBerry::
    finditem ITEM_WACAN_BERRY
    end

Chapter9_EventScript_YacheBerry::
    finditem ITEM_YACHE_BERRY
    end

Chapter9_EventScript_CobaBerry::
    finditem ITEM_COBA_BERRY
    end

Chapter10_EventScript_EjectButton::
    finditem ITEM_EJECT_BUTTON
    end

Chapter10_EventScript_ShellBell::
    finditem ITEM_SHELL_BELL
    end

Chapter10_EventScript_ExpertBelt::
    finditem ITEM_EXPERT_BELT
    end

Chapter10_EventScript_StarfBerry::
    finditem ITEM_STARF_BERRY
    end

Chapter10_EventScript_GrepaBerry::
    finditem ITEM_GREPA_BERRY
    end

Chapter10_EventScript_TamatoBerry::
    finditem ITEM_TAMATO_BERRY
    end

Chapter10_EventScript_KelpsyBerry::
    finditem ITEM_KELPSY_BERRY
    end

Chapter10_EventScript_RindoBerry::
    finditem ITEM_RINDO_BERRY
    end

Chapter10_EventScript_PayapaBerry::
    finditem ITEM_PAYAPA_BERRY
    end

Chapter11_EventScript_RingTarget::
    finditem ITEM_RING_TARGET
    end

Chapter11_EventScript_BlackSludge::
    finditem ITEM_BLACK_SLUDGE
    end

Chapter11_EventScript_PowerHerb::
    finditem ITEM_POWER_HERB
    end

Chapter11_EventScript_BlunderPolicy::
    finditem ITEM_BLUNDER_POLICY
    end

Chapter11_EventScript_PomegBerry::
    finditem ITEM_POMEG_BERRY
    end

Chapter11_EventScript_HondewBerry::
    finditem ITEM_HONDEW_BERRY
    end

Chapter11_EventScript_QualotBerry::
    finditem ITEM_QUALOT_BERRY
    end

Chapter11_EventScript_TangaBerry::
    finditem ITEM_TANGA_BERRY
    end

Chapter11_EventScript_YacheBerry::
    finditem ITEM_YACHE_BERRY
    end

Chapter11_EventScript_BabiriBerry::
    finditem ITEM_BABIRI_BERRY
    end

Chapter12_EventScript_GrassySeed::
    finditem ITEM_GRASSY_SEED
    end

Chapter12_EventScript_FlameOrb::
    finditem ITEM_FLAME_ORB
    end

Chapter12_EventScript_RazorClaw::
    finditem ITEM_RAZOR_CLAW
    end

Chapter12_EventScript_LightClay::
    finditem ITEM_LIGHT_CLAY
    end

Chapter12_EventScript_ThroatSpray::
    finditem ITEM_THROAT_SPRAY
    end

Chapter12_EventScript_LeppaBerry::
    finditem ITEM_LEPPA_BERRY
    end

Chapter12_EventScript_LiechiBerry::
    finditem ITEM_LIECHI_BERRY
    end

Chapter12_EventScript_ApicotBerry::
    finditem ITEM_APICOT_BERRY
    end

Chapter12_EventScript_ChartiBerry::
    finditem ITEM_CHARTI_BERRY
    end

Chapter12_EventScript_HabanBerry::
    finditem ITEM_HABAN_BERRY
    end

Chapter13_EventScript_PsychicSeed::
    finditem ITEM_PSYCHIC_SEED
    end

Chapter13_EventScript_MistySeed::
    finditem ITEM_MISTY_SEED
    end

Chapter13_EventScript_ToxicOrb::
    finditem ITEM_TOXIC_ORB
    end

Chapter13_EventScript_HeavyDutyBoots::
    finditem ITEM_HEAVY_DUTY_BOOTS
    end

Chapter13_EventScript_SafetyGoggles::
    finditem ITEM_SAFETY_GOGGLES
    end

Chapter13_EventScript_FocusSash::
    finditem ITEM_FOCUS_SASH
    end

Chapter13_EventScript_GanlonBerry::
    finditem ITEM_GANLON_BERRY
    end

Chapter13_EventScript_PetayaBerry::
    finditem ITEM_PETAYA_BERRY
    end

Chapter13_EventScript_ColburBerry::
    finditem ITEM_COLBUR_BERRY
    end

Chapter13_EventScript_MicleBerry::
    finditem ITEM_MICLE_BERRY
    end

Chapter14_EventScript_ElectricSeed::
    finditem ITEM_ELECTRIC_SEED
    end

Chapter14_EventScript_AirBalloon::
    finditem ITEM_AIR_BALLOON
    end

Chapter14_EventScript_LifeOrb::
    finditem ITEM_LIFE_ORB
    end

Chapter14_EventScript_UtilityUmbrella::
    finditem ITEM_UTILITY_UMBRELLA
    end

Chapter14_EventScript_SalacBerry::
    finditem ITEM_SALAC_BERRY
    end

Chapter14_EventScript_LansatBerry::
    finditem ITEM_LANSAT_BERRY
    end

Chapter14_EventScript_CustapBerry::
    finditem ITEM_CUSTAP_BERRY
    end

Chapter15_EventScript_HeatRock::
    finditem ITEM_HEAT_ROCK
    end

Chapter15_EventScript_DampRock::
    finditem ITEM_DAMP_ROCK
    end

Chapter15_EventScript_Eviolite::
    finditem ITEM_EVIOLITE
    end

Chapter15_EventScript_TerrainExtender::
    finditem ITEM_TERRAIN_EXTENDER
    end
	
Chapter15_EventScript_EnigmaBerry::
    finditem ITEM_ENIGMA_BERRY
    end

Chapter15_EventScript_JabocaBerry::
    finditem ITEM_JABOCA_BERRY
    end

Chapter15_EventScript_RowapBerry::
    finditem ITEM_ROWAP_BERRY
    end

Chapter15_EventScript_Abomasite::
    finditem ITEM_ABOMASITE
    end

Chapter15_EventScript_Cameruptite::
    finditem ITEM_CAMERUPTITE
    end

Chapter15_EventScript_Sharpedonite::
    finditem ITEM_SHARPEDONITE
    end

Chapter15_EventScript_Mawilite::
    finditem ITEM_MAWILITE
    end

Chapter15_EventScript_Beedrillite::
    finditem ITEM_BEEDRILLITE
    end

Chapter15_EventScript_Pidgeotite::
    finditem ITEM_PIDGEOTITE
    end

Chapter15_EventScript_Ampharosite::
    finditem ITEM_AMPHAROSITE
    end

Chapter15_EventScript_Heracronite::
    finditem ITEM_HERACRONITE
    end

Chapter16_EventScript_SmoothRock::
    finditem ITEM_SMOOTH_ROCK
    end

Chapter16_EventScript_IcyRock::
    finditem ITEM_ICY_ROCK
    end

Chapter16_EventScript_WeaknessPolicy::
    finditem ITEM_WEAKNESS_POLICY
    end

Chapter16_EventScript_RoomService::
    finditem ITEM_ROOM_SERVICE
    end

Chapter16_EventScript_Galladite::
    finditem ITEM_GALLADITE
    end

Chapter16_EventScript_Altarianite::
    finditem ITEM_ALTARIANITE
    end

Chapter16_EventScript_Sablenite::
    finditem ITEM_SABLENITE
    end

Chapter16_EventScript_CharizarditeX::
    finditem ITEM_CHARIZARDITE_X
    end

Chapter16_EventScript_CharizarditeY::
    finditem ITEM_CHARIZARDITE_Y
    end

Chapter16_EventScript_Steelixite::
    finditem ITEM_STEELIXITE
    end

Chapter16_EventScript_Houndoominite::
    finditem ITEM_HOUNDOOMINITE
    end

Chapter17_EventScript_SnowBall::
    finditem ITEM_SNOWBALL
    end

Chapter17_EventScript_LuminousMoss::
    finditem ITEM_LUMINOUS_MOSS
    end

Chapter17_EventScript_AssaultVest::
    finditem ITEM_ASSAULT_VEST
    end

Chapter17_EventScript_ChoiceScarf::
    finditem ITEM_CHOICE_SCARF
    end

Chapter17_EventScript_Audinite::
    finditem ITEM_AUDINITE
    end

Chapter17_EventScript_Lucarionite::
    finditem ITEM_LUCARIONITE
    end

Chapter17_EventScript_Banettite::
    finditem ITEM_BANETTITE
    end

Chapter17_EventScript_Gardevoirite::
    finditem ITEM_GARDEVOIRITE
    end

Chapter17_EventScript_Venusaurite::
    finditem ITEM_VENUSAURITE
    end

Chapter17_EventScript_Slowbronite::
    finditem ITEM_SLOWBRONITE
    end

Chapter17_EventScript_Scizorite::
    finditem ITEM_SCIZORITE
    end

Chapter17_EventScript_Sceptilite::
    finditem ITEM_SCEPTILITE
    end

Chapter17_EventScript_Manectite::
    finditem ITEM_MANECTITE
    end

Chapter18_EventScript_CellBattery::
    finditem ITEM_CELL_BATTERY
    end

Chapter18_EventScript_ChoiceBand::
    finditem ITEM_CHOICE_BAND
    end

Chapter18_EventScript_ChoiceSpecs::
    finditem ITEM_CHOICE_SPECS
    end

Chapter18_EventScript_Garchompite::
    finditem ITEM_GARCHOMPITE
    end

Chapter18_EventScript_Lopunnite::
    finditem ITEM_LOPUNNITE
    end

Chapter18_EventScript_Glalitite::
    finditem ITEM_GLALITITE
    end

Chapter18_EventScript_Absolite::
    finditem ITEM_ABSOLITE
    end

Chapter18_EventScript_Blastoistinite::
    finditem ITEM_BLASTOISINITE
    end

Chapter18_EventScript_Kangaskhanite::
    finditem ITEM_KANGASKHANITE
    end

Chapter18_EventScript_Pinsirite::
    finditem ITEM_PINSIRITE
    end

Chapter18_EventScript_Blazikenite::
    finditem ITEM_BLAZIKENITE
    end

Chapter19_EventScript_Medichamite::
    finditem ITEM_MEDICHAMITE
    end

Chapter19_EventScript_Salamencite::
    finditem ITEM_SALAMENCITE
    end

Chapter19_EventScript_Swampertite::
    finditem ITEM_SWAMPERTITE
    end

Chapter19_EventScript_Alakazite::
    finditem ITEM_ALAKAZITE
    end

Chapter19_EventScript_Gengarite::
    finditem ITEM_GENGARITE
    end

Chapter19_EventScript_Gyaradosite::
    finditem ITEM_GYARADOSITE
    end

Chapter19_EventScript_Tyranitarite::
    finditem ITEM_TYRANITARITE
    end

Chapter20_EventScript_Diancite::
    finditem ITEM_DIANCITE
    end

Chapter20_EventScript_Latiosite::
    finditem ITEM_LATIOSITE
    end

Chapter20_EventScript_Latiasite::
    finditem ITEM_LATIASITE
    end

Chapter20_EventScript_Metagrossite::
    finditem ITEM_METAGROSSITE
    end

Chapter20_EventScript_Aggronite::
    finditem ITEM_AGGRONITE
    end

Chapter20_EventScript_Aerodactylite::
    finditem ITEM_AERODACTYLITE
    end

Chapter20_EventScript_MewtwoniteX::
    finditem ITEM_MEWTWONITE_X
    end

Chapter20_EventScript_MewtwoniteY::
    finditem ITEM_MEWTWONITE_Y
    end


